### ISSUE TITLE
image corner checkboard artifacts

### ISSUE THREAD

**Issue by Darrenxc** [chaofengc/PSFRGAN#20]
have you encountered this problem? The checkboard effect happening on image corners during the training and testing phase both on 512x and 1024x. 
![00000_s004](https://user-images.githubusercontent.com/57433102/109768557-04774100-7c34-11eb-8811-5dd5b799c37b.png)
![00004](https://user-images.githubusercontent.com/57433102/109768560-06410480-7c34-11eb-922e-37c84ed0ee47.png)

**Comment by chaofengc** [comment]
I did not encounter such artifacts in my results, but I expected that such artifacts might occur because I use instance normalization in both G and D. ESRGAN and StyleGANv2 both reported similar problem of instance normalization and batch normalization. However, this is not the focus of this paper, and I did not spend much time to reproduce it. You may refer to ESRGAN and StyleGANv2  and tried to solve it.

**Comment by Darrenxc** [comment]
okay thank you
