### ISSUE TITLE
Enhanced face not blending properly(?)

### ISSUE THREAD

**Issue by Kubishime** [chaofengc/PSFRGAN#40]
I'm testing PSFRGAN on old images and it constantly places hard boxes that are either black or grey around the enhanced subject, is there something I'm missing or doing wrong?

**Comment by chaofengc** [comment]
Yes, this is probably because of blending problem. We use simple gaussian blur with `(5, 5)` kernel size to blurry the mask border. Since your picture is quite big, it is likely that small gaussian kernel fails.
https://github.com/chaofengc/PSFRGAN/blob/82a8755116d61e83a302b7e48fb61c53c36e34c9/test_enhance_single_unalign.py#L81

**Comment by Kubishime** [comment]
> Yes, this is probably because of blending problem. We use simple gaussian blur with `(5, 5)` kernel size to blurry the mask border. Since your picture is quite big, it is likely that small gaussian kernel fails.
> https://github.com/chaofengc/PSFRGAN/blob/82a8755116d61e83a302b7e48fb61c53c36e34c9/test_enhance_single_unalign.py#L81

Thank you. What you've done here is incredible.
