### ISSUE TITLE
About CelebAHQ-Test

### ISSUE THREAD

**Issue by wcy-cs** [chaofengc/PSFRGAN#44]
Thank you for sharing code of this excellent work. Can you provide the specific test images, such as CelebAHQ-Test or PSFR-RealTest? Thank you very much.

**Comment by chaofengc** [comment]
Thanks for interest.  

(1) CelebAHQ-Test is randomly synthesized with CelebAHQ-Test partition using the same degradation code as training stage. I did not save the original test set. 

(2) As for the PSFR-RealTest, you may find it in the following link: https://drive.google.com/drive/folders/1UVcADRUO_gZSDbmTujpPqU-f-eZqFO5W?usp=sharing
It is named as CelebA-TestN, which is also used in my other project: https://github.com/chaofengc/Face-SPARNet
Please note that it is a little bit different with the paper since we clean up non-face images and add some extra test images from internet.
